### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/sw-mileage-server-kt#37]
# TODO list

- [ ] 세부 항목 stuType 로직 구현 및 요청 폼 수정(stuType 받지 말기. is 태그 조합으로 백엔드에서 처리)
- [ ] 카테고리, 세부 항목 name 중복 검사 -> 중복인 카테고리, 항목 정보를 반환한다
- [ ] 학생 중복검사
- [ ] 마일리지 등록 points 받지 않고 백엔드에서 계산하는 로직 추가
- [ ] 학기별 마일리지 등록 리스트 조회 -> 전체 조회도 가능하도록 업데이트
       **v0.2 api 주소: {{base_url}}/api/{{context_admin}}/semesters/2023-02/items/records**
- [ ] 학기별 마일리지 세부 항목 리스트 조회 -> 전체 조회도 가능하도록 업데이트
       **v0.2 api 주소: {{base_url}}/api/{{context_admin}}/semesters/2023-01/items/records**

카톡방에서 나온이야기, 중간에 생각나는 개선 사항 바로 적어두기
여기서 골라서 정식 issue로 옮기고 작업 시작

**Comment by ohinhyuk** [comment]
### 마일리지 등록 API에 관한 이슈

![스크린샷 2023-08-29 오전 1 39 20](https://github.com/HGU-WALAB/sw-mileage-server-kt/assets/49269218/14c8b118-4d25-4fbf-ad0c-c6d0d51691c1)

다음은 마일리지 등록  - 수정 , 등록 API에 필요한 필드입니다.

![스크린샷 2023-08-29 오전 1 40 06](https://github.com/HGU-WALAB/sw-mileage-server-kt/assets/49269218/08a5784f-1514-42d1-91fe-b070770901c3)

현재 포스트맨에서는 학생의 이름이 없으며 불필요한 필드가 너무 많이 있습니다.
확인 부탁드립니다!

**Comment by ohinhyuk** [comment]
### DELETE관련 이슈

DELETE는 현재 한사람씩 가능하게 되어있는데
DELETE를 할 때 쿼리 파라미터로 넘겨주는 값이 무엇인가요??
학번인가요??

**Comment by yujin9747** [comment]
> ### DELETE관련 이슈
> DELETE는 현재 한사람씩 가능하게 되어있는데 DELETE를 할 때 쿼리 파라미터로 넘겨주는 값이 무엇인가요?? 학번인가요??

record id 입니다.

**Comment by ohinhyuk** [comment]
마일리지 등록 / 수정 - points 를 삭제
마일리지 조회 - studentId를 추가해서 보내줘야 함

**Comment by yujin9747** [comment]
> 마일리지 등록 / 수정 - points 를 삭제 마일리지 조회 - studentId를 추가해서 보내줘야 함

PR #43 변경사항이에요
인혁오빠가 요청한 부분 잘 반영됐는지 develop에 머지되면 한 번 확인 부탁해요
@ohinhyuk 
- 카테고리, 세부 항목 name 중복 검사
- 학생 sid 중복 검사
- 현재 모든 도메인의 form validation 테스트 코드 작성 -> 통과함
- 학기별 마일리지 등록 리스트 조회 -> records에 sid, modDate 추가
v0.2 api 주소: {{base_url}}/api/{{context_admin}}/semesters/{학기 이름}/items/records
- 엑셀 다운로드 필드 버그 수정 -> 테스트 코드도 작성함
